# This is a basic workflow to help you get started with Actions

name: Hexo Blog Deploy CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Set Node.js
        uses: actions/setup-node@v1 
            
      - name: Set Git
        env:
          HEXO_DEPLOY_GIT_SSH_PRIVATE_KEY: ${{secrets.HEXO_DEPLOY_GIT_SSH_PRIVATE_KEY}}
        run: |
          # set up private key for deploy
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_GIT_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          # set git infomation
          git config --global user.name "${{secrets.HEXO_DEPLOY_GIT_NAME}}"
          git config --global user.email "${{secrets.HEXO_DEPLOY_GIT_EMAIL}}"

      - name: install Hexo Cli
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
          npm install
          npm audit fix

      - name: install hexo Plug and Hexo Theme # npm ls --depth 0 可查看自己安装了哪些插件
        run: |
          npm install hexo-deployer-git --save
          npm install hexo-deployer-archive --save
          npm install hexo-generator-category --save
          npm install hexo-generator-feed --save
          npm install hexo-generator-index --save
          npm install hexo-generator-tag --save
          npm install hexo-renderer-ejs --save
          npm install hexo-renderer-marked --save
          npm install hexo-renderer-stylus --save
          npm install hexo-server --save
          git clone ${{secrets.HEXO_THEME_GIT_URL}} themes/${{secrets.HEXO_THEME_NAME}}
          npm audit fix

      - name: deploy Github Pages
        run: |
          hexo clean && hexo d -g
